---
 - name: This play will demonstrate apt module
   hosts: all
   tasks:
   - name: Install vim editor
     apt: name=vim state=latest update_cache=yes

   - name: install tree utility
     apt: name=tree state=latest update_cache=yes
...
