  - name: Configure Web Root folder on Ubuntu
    copy: src=default dest=/etc/nginx/sites-available/default
    when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
    notify:
        - restart nginx web server

  - name: Configure Web Root folder on CentOs
    copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
    when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
    notify:
        - restart nginx web server


